apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: webserver
  name: webserver-service
  namespace: webserverns
spec:
  selector:
    app: webserver-depl
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
